[[language]]
name = "python"
formatter = { command = "black", args = ["--quiet", "-"] } # , "--line-length=79"
auto-format = false
config = { pylsp.plugins.rope_autoimport.enabled = true, pylsp.plugins.pylint.enabled = true }
