[[language]]
name = "python"
formatter = { command = "black", args = ["--quiet", "-"] } # , "--line-length=79"
auto-format = true
config = { pylsp.plugins.rope_autoimport.enabled = false, pylsp.plugins.pylint.enabled = false }
