default_flags = "g"

[[verbs]]
invocation = "edit"
key = "Ctrl-e"
shortcut = "e"
execution = "$EDITOR {file}"
leave_broot = false

[[verbs]]
key = "Ctrl-j"
execution = ":line_down"

[[verbs]]
key = "Ctrl-k"
execution = ":line_up"

[[verbs]]
invocation = "touch {filename}"
execution = "touch {directory}/{filename}"
leave_broot = false
